### ISSUE TITLE
多渠道打包

### ISSUE THREAD

**Issue by jinzw1993** [D-clock/Doc#1]
小白第一次多渠道打包。多渠道打包需要多长时间啊。我的为什么我卡了快好久也没成功啊。

**Comment by D-clock** [comment]
看你工程代码的复杂程度，依赖的模块越多，打包越久。我打20个包差不多要十几分钟。卡了好久没成功，你看下报错的LOG排查一下问题。

**Comment by jinzw1993** [comment]
我的是有个地方写错了。卡好就可能是代码学错了。
